export enum MODAL_NAMES {
  LOGIN_OPTIONS_MODAL = "LOGIN_OPTIONS_MODAL",
  LOGIN_WITH_EMAIL_MODAL = "LOGIN_WITH_EMAIL_MODAL",
  REGISTER_OPTIONS_MODAL = "REGISTER_OPTIONS_MODAL",
  REGISTER_FORM_MODAL = "REGISTER_FORM_MODAL",
  REGISTER_EMAIL_CONFIRMATION = "REGISTER_EMAIL_CONFIRMATION",
  ACTIVATION_ACCOUNT_INSTRUCTION = "ACTIVATION_ACCOUNT_INSTRUCTION",
}
